### ISSUE TITLE
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/packagename/databases/downloader_db

### ISSUE THREAD

**Issue by GrishinSergey** [alirezat775/downloader#4]
hello, when using the library, I encountered a problem:

sometimes lib calls `onFailure` with such reason message:
```
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/packagename/databases/downloader_db
```

1) maybe better to pass exception as parameter, for its future custom handing in client code? F.ex, if it is network exception, it can be handled in one way, if this is IOException -- another way to handle it.
2) actually I can't understand, why it throws exception like in title of this issue. 

If this info will help with understanding:
I'm using this lib for loading images in recyclerview as context I'm using `applicationContext`.
Can it be cuz, fast scrolling of recyclerview and, in this reason, several instances of `Downloader`, creating?

**Comment by alirezat775** [comment]
Hi, this exception raised when creating multiple instances from downloader because you create a new thread for doing a transaction on the database, in downloader library using room library for store download state, so a room doesn't let create a new transaction when close that's already. 
You shouldn't use downloader for loading image, so you can use a specific library for image loading like glide, picasso or etc.
An otherwise when using downloader instead of  image loader probably you must be solved multi-threading issue

**Comment by GrishinSergey** [comment]
@alirezat775 , thank you for so quick answer. I decided to use this lib, cuz I don't need to show image in ui, just download it to file storage + progress and beautiful api. So, am I right, if say, for fixing my issue, all I need is create a queue of downloading tasks and just load files one-by-one?

**Comment by alirezat775** [comment]
@GrishinSergey your welcome, currently supported light-weight queue in the library, so that's mean you can execute download task with a limit resources also you can create a pool of downloader for downloading item with priority in the background and handle multiple downloader objects in the downloader-pool

**Comment by GrishinSergey** [comment]
@alirezat775, can you show an example, how to use this queue? For now I see database and I understood fo myself that this is that queue about what you saying. Can you show some examples?

**Comment by alirezat775** [comment]
In the library use android looper for handle multi-thread actions, they implemented in parent asyncTask class.
[This sample](https://github.com/raminduw/ThreadPoolExecutor) maybe helpful for implementation thread-pool

**Comment by GrishinSergey** [comment]
Okay, thank you, alirezat775. I think, this issue can be closed?

**Comment by alirezat775** [comment]
I close the issue, good luck
